### ISSUE TITLE
WebSocket can not connect to websocket.org echo server

### ISSUE THREAD

**Issue by bsapwindows** [c-smile/sciter-sdk#77]
``` javascript
var socket = Net.WebSocket.connect("ws://echo.websocket.org/");
socket.on("error", function(msg){ $(#errmsg).$append(<li>{msg}</li>); });
```

Error message is _**address not available**_

Using x64 sciter.exe in SDK to load the HTML.

It works fine with the demo node echo server listening on address like `ws://localhost:8126/`.

**Comment by c-smile** [comment]
While trying to ping that address I am getting this:

```
Pinging echo.websocket.org [174.129.224.73] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 174.129.224.73:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),

```

**Comment by bsapwindows** [comment]
I'm getting the same. Probably they blocked ICMP?

Try the echo server on [http://websocket.org/echo.html](http://websocket.org/echo.html), the client on the page also works with demo echo server.

I'm testing a websocket server written in go, getting 400/403 code, not sure if it's the server's problem or the client's. So I tried websocket.org, the client on the page works with my go echo server.

**Comment by c-smile** [comment]
Use this url:  "ws://echo.websocket.org:80/" ( explicit port declaration ).

Me culpa. Fixed here already, will appear in the next build.

**Comment by bsapwindows** [comment]
Yes it works now with port declaration. Nice job on fixing it so quickly. :clap: 

Although my own go echo server is still not working as intended... :joy: 

My server can be connected with the client on http://websocket.org/echo.html, but with my TIScript client I'm getting _**got bad status connecting to ws://localhost:7474/echo: HTTP/1.1 403 Forbidden**_, any idea what could cause this?

**Comment by c-smile** [comment]
Your server returns 403 so it makes sense to check there.

**Comment by bsapwindows** [comment]
I finally figured it out...

The official go example of websocket echo server doesn't work because it checks if the Origin header is a valid URL. Sciter doesn't perform like browsers, which send the Origin header, so my server rejects it's request.

What an adventure for a noob like me... haha

I'm closing the issue now, you can reopen it if you need. :smiley: 

Off topic, it seems Sec-WebSocket-Key in sciter's request header has a fixed value, not sure if it's by design.
